version: '3.3'
services:
    influxdb:
        container_name: influxdb
        ports:
            - '8086:8086'
        volumes:
            - '~/influx:/var/lib/influxdb'
        network_mode: influxdb-telegraf-net
        image: 'influxdb:2.0'


    mosquitto:
      container_name: mosquitto
      ports:
        - '1883:1883'
        - '9001:9001'
      volumes:
        - './mosquitto-conf:/mosquitto/config/'
      image: eclipse-mosquitto
        
    telegraf:
        container_name: telegraf
        volumes:
             - './telegraf-conf:/etc/telegraf/'
        network_mode: influxdb-telegraf-net
        depends_on:
             - "influxdb"
             - "mosquitto"         
        image: telegraf

