version: '3.3'
services:
    influxdb:
        container_name: influxdb
        ports:
            - '8086:8086'
        volumes:
            - '~/influx:/var/lib/influxdb'
        network_mode: influxdb-telegraf-net
        image: 'influxdb:2.0'

    telegraf:
        container_name: telegraf
        volumes:
             - './telegraf-conf:/etc/telegraf/'
        network_mode: influxdb-telegraf-net
        depends_on:
             - "influxdb"
        image: telegraf